# This rule is not used by the project apps-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to apps.otterscale.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: apps-operator
    app.kubernetes.io/managed-by: kustomize
    rbac.authorization.k8s.io/aggregate-to-view: "true"
  name: simpleapp-viewer-role
rules:
- apiGroups:
  - apps.otterscale.io
  resources:
  - simpleapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.otterscale.io
  resources:
  - simpleapps/status
  verbs:
  - get
